# Generated by Django 4.2.6 on 2023-11-01 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='Действие')),
                ('habit_datetime', models.DateTimeField(verbose_name='Дата выполнения')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('pleasant_sign', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('frequency', models.IntegerField(blank=True, default=1, null=True, verbose_name='Интервал (дней)')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.IntegerField(verbose_name='Время на выполнение')),
                ('public_sign', models.BooleanField(blank=True, default=False, null=True, verbose_name='Публичный')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелеец')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='the_habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
