# Generated by Django 4.2.6 on 2023-11-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_habits', '0002_alter_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='launched',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Задание выполняется'),
        ),
    ]
